name: Snowflake Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:

  deploy-dev:
    runs-on: ubuntu-latest

    env:
      TF_VAR_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      TF_VAR_username: ${{ secrets.SNOWFLAKE_USER }}
      TF_VAR_role: ${{ secrets.SNOWFLAKE_ROLE }}
      TF_VAR_private_key_path: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Write private key to file
        run: |
          cat << 'EOF' > /tmp/rsa_key.p8
          ${{ secrets.SNOWFLAKE_PASSWORD }}
          EOF
          chmod 600 /tmp/rsa_key.p8
          echo "--- First line ---"
          head -1 /tmp/rsa_key.p8
          echo "--- Last line ---"
          tail -1 /tmp/rsa_key.p8
          echo "--- Line count ---"
          wc -l /tmp/rsa_key.p8

      - name: Terraform Init DEV
        working-directory: environments/dev
        run: terraform init -upgrade

      - name: Terraform Validate DEV
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform Plan DEV
        working-directory: environments/dev
        run: terraform plan

      - name: Terraform Apply DEV
        working-directory: environments/dev
        run: terraform apply -auto-approve

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: production

    env:
      TF_VAR_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      TF_VAR_username: ${{ secrets.SNOWFLAKE_USER }}
      TF_VAR_role: ${{ secrets.SNOWFLAKE_ROLE }}
      TF_VAR_private_key_path: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PATH }}

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Write private key to file
        run: |
          cat << 'EOF' > /tmp/rsa_key.p8
          ${{ secrets.SNOWFLAKE_PASSWORD }}
          EOF
          chmod 600 /tmp/rsa_key.p8
          echo "--- First line ---"
          head -1 /tmp/rsa_key.p8
          echo "--- Last line ---"
          tail -1 /tmp/rsa_key.p8
          echo "--- Line count ---"
          wc -l /tmp/rsa_key.p8

      - name: Terraform Init PROD
        working-directory: environments/prod
        run: terraform init -upgrade

      - name: Terraform Validate PROD
        working-directory: environments/prod
        run: terraform validate

      - name: Terraform Plan PROD
        working-directory: environments/prod
        run: terraform plan

      - name: Terraform Apply PROD
        working-directory: environments/prod
        run: terraform apply -auto-approve
        